spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interviewdans
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


application:
  security:
    jwt:
      secret-key: 4A404E635266556A586E3272357538782F413F4428472B4B6150645367566B59
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
